#ifndef AZP_DISC_H
#define AZP_DISC_H

#include <stdint.h>

#define AZP_DISC_FS_LEFT_UPX			0
#define AZP_DISC_FS_LEFT_UPY			(2*(GLCD_Y_SIZE/6))
#define AZP_DISC_FS_RIGHT_DOWNX			GLCD_X_SIZE
#define AZP_DISC_FS_RIGHT_DOWNY			GLCD_Y_SIZE
#define AZP_DISC_FS_SIZEY				(AZP_DISC_FS_RIGHT_DOWNY - AZP_DISC_FS_LEFT_UPY)


#define AZP_DISC_FS_PARTS_WIDTH			1
#define AZP_DISC_FS_XRANGE				(GLCD_X_SIZE-8)
#define AZP_DISC_FS_PARTS_COUNT			(AZP_DISC_FS_XRANGE/AZP_DISC_FS_PARTS_WIDTH)
#if(AZP_FS_XRANGE != (AZP_DISC_FS_PARTS_WIDTH * AZP_DISC_FS_PARTS_COUNT))
	//#error "FILLED SCOPE PARTS WIDTH is NOT OPTIMAL"
#endif

#define AZP_DISC_TID_STR_LEFT_UPX		(GLCD_X_SIZE/3)
#define AZP_DISC_TID_STR_LEFT_UPY		((4*AZP_DISC_FS_SIZEY)/5)
#define AZP_DISC_TID_STR_RIGHT_DOWNX	(2*(GLCD_X_SIZE/3))
#define AZP_DISC_TID_STR_RIGHT_DOWNY	AZP_DISC_FS_SIZEY

extern uint8_t AZP_Disc(void);

#endif

