#ifndef AZP_MENU_H
#define AZP_MENU_H

#include <stdint.h>

#define AZP_MENU_LEFT_UPX	0
#define AZP_MENU_LEFT_UPY	(GLCD_Y_SIZE/6)
#define AZP_MENU_DOWN_RIGHTX GLCD_X_SIZE	
#define AZP_MENU_DOWN_RIGHTY GLCD_Y_SIZE	
#define AZP_MENU_MIDWIN_SIZEX	(AZP_MENU_DOWN_RIGHTX - AZP_MENU_LEFT_UPX)
#define AZP_MENU_MIDWIN_SIZEY	(AZP_MENU_DOWN_RIGHTY - AZP_MENU_LEFT_UPY)

#define AZP_SUBMEN_STR_POSX	30
#define AZP_SUBMEN_STR_POSY	20
#define AZP_SUBMEN_STR_ENDX	(AZP_MENU_MIDWIN_SIZEX - AZP_SUBMEN_STR_POSX)
#define AZP_SUBMEN_STR_ENDY	(AZP_SUBMEN_STR_POSY + 40)

#define AZP_SUBMEN_POSX	30
#define AZP_SUBMEN_POSY	70
#define AZP_SUBMEN_ENDX	(AZP_MENU_MIDWIN_SIZEX - AZP_SUBMEN_POSX)
#define AZP_SUBMEN_ENDY	(AZP_MENU_MIDWIN_SIZEY-10)

#define AZP_SLIDER_POSX_MIN	31
#define AZP_SLIDER_POSX_MAX	(GLCD_X_SIZE - AZP_SLIDER_POSX_MIN)
#define AZP_SLIDER_POSY_MIN	80
#define AZP_SLIDER_POSY_MAX	110

#define AZP_MAN_GB_MINERAL_MIN	0
#define AZP_MAN_GB_MINERAL_MAX	300

// CAVITY TEST is removed from system settings // 
typedef enum {
	AZP_SYS_FERRO_ELIMINATE = 0,
	AZP_SYS_DEPTH,
	AZP_SYS_LANG,
	AZP_SYS_FACTORY,
	AZP_SYS_MAX_POS = AZP_SYS_FACTORY,
	
	AZP_SYS_POS_CNT
} eAZPSET;

#define AZP_GB_AUTO_SEL	0

typedef enum {
	GB_IDLE = 0,
	GB_CONFIRM_REQ,
	GB_CANCEL_REQ,
	GB_END_WAIT,

	GB_STATES_COUNT
} eGBStates;

#define DPT1_POS_AUTO_GB	0
#define DPT1_POS_MAN_GB		1

#define AZP_GB_COIL_SIZEX	108
#define AZP_GB_COIL_SIZEY	60
#define AZP_GB_ANIM_MS		250

extern uint8_t AZP_Menu(void);

#endif

