#ifndef APP_PIC_H
#define APP_PIC_H

#include "GUI_Type.h"

extern GUI_CONST_STORAGE GUI_BITMAP bmSeggerLogo140x70;
extern GUI_CONST_STORAGE GUI_BITMAP bmSeggerLogo70x35;
extern GUI_CONST_STORAGE GUI_BITMAP _bmLogoSegger_40x20;
extern GUI_CONST_STORAGE GUI_BITMAP bmGB;
extern GUI_CONST_STORAGE GUI_BITMAP bmSearchMode;
extern GUI_CONST_STORAGE GUI_BITMAP bmVolume;
extern GUI_CONST_STORAGE GUI_BITMAP bmSensitivity;
extern GUI_CONST_STORAGE GUI_BITMAP bmLanguage;
extern GUI_CONST_STORAGE GUI_BITMAP bmGain;
extern GUI_CONST_STORAGE GUI_BITMAP bmSearch;
extern GUI_CONST_STORAGE GUI_BITMAP bmUgurBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmBrightness;
extern GUI_CONST_STORAGE GUI_BITMAP bmHelp;
extern GUI_CONST_STORAGE GUI_BITMAP _bmRect_60x60;

// Small Menu Icons //
extern GUI_CONST_STORAGE GUI_BITMAP bmGBSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmVolumeSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSensitivitySmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSearchModeSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmLanguageSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmGainSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSearchSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmUgurSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmHelpSmall;
//extern GUI_CONST_STORAGE GUI_BITMAP bmBrightnessSmall;

// Application ICONs //
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconMineralization;
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconUgurDetector;
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconSensitivity;
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconSearchMode;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconBCoil;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconMCoil;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconSCoil;
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconGain;
//extern GUI_CONST_STORAGE GUI_BITMAP bmIconVolume;
extern GUI_CONST_STORAGE GUI_BITMAP bmRead;

// SMALL Language StatusBar Icons // 
extern GUI_CONST_STORAGE GUI_BITMAP bmIconArabic;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconBulgarian;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconFrench;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconGerman;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconGreek;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconEnglish;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconRussian;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconPersian;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconTurkish;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconSpanish;
// BIG Language Setting Popup Icons // 
extern GUI_CONST_STORAGE GUI_BITMAP bmArabicBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmBulgarianBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmFrenchBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmGermanBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmGreekBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmEnglishBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmRussianBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmPersianBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmTurkishBig;
extern GUI_CONST_STORAGE GUI_BITMAP bmSpanishBig;
extern unsigned char acClaySmallJPEGBin[];

// Icons with AlphaChannel // 
extern GUI_CONST_STORAGE GUI_BITMAP bmClock;
extern GUI_CONST_STORAGE GUI_BITMAP bmBrowser;
extern GUI_CONST_STORAGE GUI_BITMAP bmDate;
extern const unsigned char acFramed24B;
extern GUI_CONST_STORAGE GUI_BITMAP bmEmail;
extern GUI_CONST_STORAGE GUI_BITMAP bmHund;
extern GUI_CONST_STORAGE GUI_BITMAP bmPassword;
extern GUI_CONST_STORAGE GUI_BITMAP bmRemote;
extern GUI_CONST_STORAGE GUI_BITMAP bmSystem;
extern GUI_CONST_STORAGE GUI_BITMAP bmToucan;
extern GUI_CONST_STORAGE GUI_BITMAP bmWrite;

// Soil Type Icons //
extern GUI_CONST_STORAGE GUI_BITMAP bmClay;
extern GUI_CONST_STORAGE GUI_BITMAP bmPeaty;
extern GUI_CONST_STORAGE GUI_BITMAP bmSaline;
extern GUI_CONST_STORAGE GUI_BITMAP bmSandy;
extern GUI_CONST_STORAGE GUI_BITMAP bmSilty;
extern GUI_CONST_STORAGE GUI_BITMAP bmClaySmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmPeatySmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSalineSmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSandySmall;
extern GUI_CONST_STORAGE GUI_BITMAP bmSiltySmall;

// StatusBAR Pictures //
extern GUI_CONST_STORAGE GUI_BITMAP bmSBBackground;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_100;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_90;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_75;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_60;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_55;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_45;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_30;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_10;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_0;

// Demo Pictures //
// SB //
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_0;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_10;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_30;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_45;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_0;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_0;
extern GUI_CONST_STORAGE GUI_BITMAP bmBat_0;
extern GUI_CONST_STORAGE GUI_BITMAP bmSBBackground;
// RM //
extern GUI_CONST_STORAGE GUI_BITMAP bmRMGB;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMSearch;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMSens;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMLang;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMVol;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMBright;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMHelp;
extern GUI_CONST_STORAGE GUI_BITMAP bmRMBack;
// OTOMATIC //
extern GUI_CONST_STORAGE GUI_BITMAP bmcavity;
extern GUI_CONST_STORAGE GUI_BITMAP bmferros;
extern GUI_CONST_STORAGE GUI_BITMAP bmnferros;
extern GUI_CONST_STORAGE GUI_BITMAP bmgold;
extern GUI_CONST_STORAGE GUI_BITMAP bmmineral;
extern GUI_CONST_STORAGE GUI_BITMAP bmBW;
extern GUI_CONST_STORAGE GUI_BITMAP bmColored;
extern GUI_CONST_STORAGE GUI_BITMAP bmGStrBack;
extern GUI_CONST_STORAGE GUI_BITMAP bmInfoBack;
extern GUI_CONST_STORAGE GUI_BITMAP bmNOFerros;
extern GUI_CONST_STORAGE GUI_BITMAP bmYESFerros;
extern GUI_CONST_STORAGE GUI_BITMAP bmOTOGBack;
extern GUI_CONST_STORAGE GUI_BITMAP bmscrStrBack;
// STANDARD //
extern GUI_CONST_STORAGE GUI_BITMAP bmGgBACK;
extern GUI_CONST_STORAGE GUI_BITMAP bmGgBACKMask;
extern GUI_CONST_STORAGE GUI_BITMAP bmScrNameBACK;
extern GUI_CONST_STORAGE GUI_BITMAP bmSTDDeskBACK;
extern GUI_CONST_STORAGE GUI_BITMAP bmColored;
extern GUI_CONST_STORAGE GUI_BITMAP bmBW;
// depth //
extern GUI_CONST_STORAGE GUI_BITMAP bmDptBACK;
extern GUI_CONST_STORAGE GUI_BITMAP bmSel;
extern GUI_CONST_STORAGE GUI_BITMAP bmUnsel;
extern GUI_CONST_STORAGE GUI_BITMAP bmAction;
		

#endif
