obj-m += circular_file.o

circular-file-objs := main.o circular_file.o 

KERNELDIR=/home/modeo/workspace_cdt/linux-03.00.01.06

all:
	make -C $(KERNELDIR) M=$(PWD) modules

clean:
	rm *.o
	rm modules.order
	rm .*.ko.cmd
	rm .*.o.cmd
	rm Module.symvers
	rm *.ko
	rm *.mod.c
	rm -r ./.tmp_versions

